name: ESLint check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main, dev]

jobs:
    eslint:
        permissions:
            contents: read
            packages: read

        runs-on: ubuntu-latest

        steps:
            - name: ğŸ”¨ checkout repository
              uses: actions/checkout@v5
            - name: ğŸ”¨ use Node.js 22
              uses: actions/setup-node@v5
              with:
                  node-version: "22"
            - name: ğŸ”¨ install package dependencies
              run: npm ci
            - name: ğŸ”¨ run lint check
              run: npm run check:lint
